# Generated by Django 4.1.2 on 2022-10-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_variacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variavel', 'verbose_name_plural': 'Variaveis'},
        ),
    ]
